name: CallCoreDemo
on:
    push:
        branches:
            - main
    pull_request_target:
        types: [ opened, synchronize]
    workflow_dispatch:
jobs:
    Writing-files:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: |
                sleep 30
                echo "hello"

            - name: Turnstyle
              uses: softprops/turnstyle@v1
              with:
                continue-after-seconds: 30
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: step2
              run: |
                  sleep 30
                  echo "hello"