name: cluster-info
"on":
  workflow_dispatch:
    inputs:
      archive:
        description: Archive the artifact
        type: boolean
      logLevel:
        description: logging level
        default: info
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: Test scenario tags
        type: string
  push:
    branches:
      - master
    paths:
      - cluster-info/**
jobs:
  cluster-info:
    uses: ./.github/workflows/simple-shape.yaml
    with:
      directory: cluster-info
      parameters: |
        export archive=${{ toJSON(inputs.archive) }}
        export logLevel=${{ toJSON(inputs.logLevel) }}
        export tags=${{ toJSON(inputs.tags) }}
      phase-locks: test-team-1-core-jenkins-test-app-1-cluster-info-cdBuild,lock1,lock2
      runs-on: ubuntu-latest
      task: echo "hello world"
      slack-channel: some-channel
    secrets:
      SLACK_TOKEN: "do-not-use-this-token"
